GitHubSync update - master
Particular/TimeoutMigrationTool pull request #154
Opened 2021-01-12 19:13 UTC by particularbot6

This is an automated synchronization PR.

The following source template repositories were used:
* particular/RepoStandards

2021-01-25 13:23 UTC, WilliamBZA commented
Dear future taskforce: You're welcome for the little bit I did

2021-01-29 22:09 UTC, SeanFeldman commented
> Dear future taskforce: You're welcome for the little bit I did

![image](https://user-images.githubusercontent.com/1309622/106332360-e50b8380-6243-11eb-8457-ccc08cf6ee7e.png)

2021-01-29 23:01 UTC, bording requested changes

2021-01-29 23:10 UTC, SeanFeldman commented on src/TimeoutMigrationTool.NHibernate.AcceptanceTests/NHibernateTimeoutsSourceTests.cs
> +                    break;
ah, right. Fixing.

2021-01-29 23:35 UTC, bording approved these changes

2021-01-29 23:36 UTC, merged